### ISSUE TITLE
HDD 'naming'

### ISSUE THREAD

**Issue by mg-man** [saybur/scuznet#13]
Not really an issue... more an observation.  In the INI, you have...

[hdd]
Controls the hard drive emulation. This section is optional and may be omitted. Up to four sections are supported: [hdd1] (aliased to [hdd]), [hdd2], [hdd3], and [hdd4], allowing up to four virtual hard drives.

Shouldn't the 'drives' really be hdd0, hdd1, hdd2, hdd3?  IoW, shouldn't "hdd" alias to "hdd0"?

**Comment by saybur** [comment]
My apologies for the long delay, I've had this project on the back burner for a while.

The documentation is correct for the device's behavior, with drives being indexed from 1. In retrospect this was not the right way to do this - SCSI IDs start at zero, so it would have made more sense to index from 0 instead like you described.

With config files in the wild I'm inclined to leave things as they are at this point. If there is consensus to change this I'm open to doing that. It would be easy to implement by just modifying config.c to change `hddsel = section[3] - '1';` to `'0'` instead.
