### ISSUE TITLE
Question about hardware issue

### ISSUE THREAD

**Issue by ronangaillard** [saybur/scuznet#2]
Hi,

I went through your repo and you stand in the hardware part that

`The '574 is unnecessary and a result of a bad design choice on my part. It could be replaced with a '245.`

I'm not sure to understand why. You would need a buffer to latch the data lines, so the 574 seems a good choice. What would the 245 improve ?

Thanks in advance :)

**Comment by saybur** [comment]
Discussed [here](https://68kmla.org/forums/topic/58413-scsi-to-ethernet-adapter-on-new-hardware/?do=findComment&comment=655814).
