### ISSUE TITLE
Nuvolink Stability

### ISSUE THREAD

**Issue by saybur** [saybur/scuznet#9]
The Nuvolink emulation is unstable on some systems. There seems to be a general correlation between faster systems and more stability, but this is not 1:1. Known trouble spots:

- Emulation is stable on a IIci running system 7.5.5.
- Emulation is stable on a LC running 7.0.1 (at least during initial protocol development, there may have been regressions).
- Emulation is not stable on SE/30s by @superjer2000 and Chopsticks
- Attempting to mount volumes on a SE FDHD running 7.0.1 causes a divide by zero error.

There is a more extensive discussion about this on the 68kmla forum thread. It would be helpful if other users experiencing trouble commented on this issue.

**Comment by saybur** [comment]
Significant improvements to Nuvolink stability are on the 'netdev' branch. Stable when tested on my SE, IIsi, and IIci. Needs to be tested on an SE/30, which is the system that most users have reported problems with.

AppleTalk is slow on the SE (only ~8.5KB/s) and there isn't any obvious reason why in Wireshark or on the debugging output. For comparison, I'm getting 125KB/s on the IIsi and 165KB/s on the IIci.

**Comment by superjer2000** [comment]
Still freezing on SE/30 - tried with Fetch on system 7.5.3.  Slow ramp up but froze within ~45 seconds of transfer starting with solid light.  Was able to transfer file 6MB with AppleTalk at a reasonable speed (~65kb/s)

**Comment by saybur** [comment]
Per forum thread, this should be fixed as of commit 30f6cb3a3b6ea9e641d9e517019c296c0c8c40b4. Will reopen if more problems develop.
